apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot003
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot003
  name: chatbot003
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
