apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot003
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot003
  name: chatbot003
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot003
