apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot003
  janus-idp.io/tekton: chatbot003
  backstage.io/kubernetes-id: chatbot003
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: chatbot003
resources:
  - application-dev.yaml
